### PR TITLE
Use new create event

### PR DESCRIPTION
**Pull request by parberge**
Use the `create_event` function instead to move towards the new API.
Relates to #125

### CODE REVIEW

**Comment by parberge** [comment]
@mattiaslundberg Any clues on why the integration tests fail?

Got this weird error:
```
ERROR    chalicelib.lib.helpers:helpers.py:60 Unable to validate date 2020-07-23. Error was: unconverted data remains: -23
```

**Comment by mattiaslundberg** [comment]
That error should not affect the listing, (listing reuses parse date and handles multiple formats, if one of them fails it will continue with the next). Seems like it's a weird response when adding, I get a 200 response with the following data `{"ConsumedCapacity": {"TableName": "dev_event", "CapacityUnits": 1.0}}` when running add locally. Not sure if that's correct or an error? My guess is that the event for some reason doesn't get saved...

**Comment by parberge** [comment]
> That error should not affect the listing, (listing reuses parse date and handles multiple formats, if one of them fails it will continue with the next). Seems like it's a weird response when adding, I get a 200 response with the following data `{"ConsumedCapacity": {"TableName": "dev_event", "CapacityUnits": 1.0}}` when running add locally. Not sure if that's correct or an error? My guess is that the event for some reason doesn't get saved...

It was my thought as well, but when I run the integration tests for this branch I can see that everything is added correctly 🤔

**Comment by parberge** [comment]
@mattiaslundberg I found the issue. The new event expects the user_id to be part of the event, which it didn't before. I need to update our factory function

**Comment by parberge** [comment]
@mattiaslundberg So the tests passes now, even though I haven't updated any of the tests. I thought I would need to update the mocked data to make it represent this change I made 🤔

**Pull request merged**
